-- MySQL Script generated by MySQL Workbench
-- 12/29/16 13:28:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema rs_org_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rs_org_schema` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `rs_org_schema` ;

-- -----------------------------------------------------
-- Table `rs_org_schema`.`USER_INFO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rs_org_schema`.`USER_INFO` ;

CREATE TABLE IF NOT EXISTS `rs_org_schema`.`USER_INFO` (
  `USER_ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户编号',
  `USER_NAME` VARCHAR(45) NOT NULL COMMENT '用户名',
  `USER_PASSWD` VARCHAR(45) NOT NULL COMMENT '用户密码',
  `CREATE_TIME` TIMESTAMP NOT NULL DEFAULT current_timestamp COMMENT '创建时间',
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC),
  UNIQUE INDEX `USER_NAME_UNIQUE` (`USER_NAME` ASC)
  )
ENGINE = InnoDB 
DEFAULT CHAR SET = utf8
COMMENT = '用户信息表';

